In [1]:
import pandas as pd

In [2]:
DATA_PATH = "Train_k2pandc.csv"
# assert os.path.exists(DATA_PATH), f"Dataset not found at {DATA_PATH}"

df = pd.read_csv(DATA_PATH)
print("Dataset loaded. Shape:", df.shape)
df.head()

Dataset loaded. Shape: (3204, 94)

,pl_name,hostname,default_flag,disposition,disp_refname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,...,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,rowupdate,pl_pubdate,releasedate
0,EPIC 211590050.01,EPIC 211590050,1,CANDIDATE,Castro-Gonz&aacute;lez et al. 2022,1,0,Transit,2022,K2,...,-0.172,11.958,0.020,-0.020,13.3081,0.000210,-0.000210,2022-04-18,2022-01,2022-04-18
1,EPIC 211600389.01,EPIC 211600389,1,FALSE POSITIVE,Yu et al. 2018,1,0,Transit,2018,K2,...,-0.172,12.885,0.024,-0.024,14.0604,0.006177,-0.006177,2019-02-26,2018-07,2019-02-26
2,EPIC 211600632.01,EPIC 211600632,1,FALSE POSITIVE,Yu et al. 2018,1,0,Transit,2018,K2,...,NaN,14.142,0.076,-0.076,19.2896,0.008025,-0.008025,2019-02-26,2018-07,2019-02-26
3,EPIC 211604981.01,EPIC 211604981,1,FALSE POSITIVE,Yu et al. 2018,1,0,Transit,2018,K2,...,-0.069,11.531,0.018,-0.018,12.6528,0.000193,-0.000193,2019-02-26,2018-07,2019-02-26
4,EPIC 211606790.01,EPIC 211606790,0,CANDIDATE,Kruse et al. 2019,1,0,Transit,2018,K2,...,-0.103,10.398,0.025,-0.025,12.0575,0.000170,-0.000170,2018-02-15,2018-03,2018-02-15